config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'task/:id', to: 'tasks#show', as: :task
  get 'task/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'task/:id', to: 'tasks#update'
  delete 'task/:id', to: 'tasks#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    id = params[:id]
    @task = Task.find(id)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    id = params[:id]
    @task = Task.find(id)
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container mt-4" >
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<div class="d-flex flex-column">
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit %>
  <% end %>

<p class="mt-3"><%= link_to "Go back to tasks", tasks_path %></p>
<p><%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p>
</p>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<div class="d-flex flex-column">
  <%@tasks.each do |task|%>
  <div>
  <input type="checkbox" id="task" name="task"
  <label for="task"><%= link_to task.title, task_path(task)%></label>
  </div>
  <%end%>

  <p><%= link_to "Add a task", tasks_new_path %></p>

</div>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>

<%= simple_form_for(@task) do |f| %>
  <%= f.input :title %>
  <%= f.input :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<div class="p-3">
<h1><%=@task.title%></h1>
<p><%= link_to "Edit this task", task_edit_path(@task) %></p>
</div>
<div class="p-3 bg-light text-dark bg-opacity-25"><p><%=@task.details%></p></div>
<div class="p-3"><p>
<%unless @task.completed%>
<%="❌ This task is not completed yet"%>
<%else%>
<%="✅ This task is completed!"%>
<%end%>
</p>

<p><%= link_to "Go back to tasks", tasks_path %></p>
<p><%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %></p>
</p>
</div>